# Generated by Django 5.0.7 on 2024-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
